NVMem: fix build issue when FILE_BACKED_NV is set to 0
If FILE_BACKED_NV is set to NO(0), the `delete` variable is unused,
causing a compiler warning:

    Platform/src/NVMem.c: In function ‘_plat__NVDisable’:
    Platform/src/NVMem.c:185:9: error: unused variable ‘delete’ [-Werror=unused-variable]
      185 |     int delete = ((intptr_t)platParameter != 0)
          |         ^~~~~~
    cc1: all warnings being treated as errors
    make[2]: *** [Makefile:2674: Platform/src/libplatform_a-NVMem.o] Error 1

Use NOT_REFERENCED() to silence this warning.

Signed-off-by: Stefano Garzarella <sgarzare@redhat.com>